# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\design\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Form):
        Form.setObjectName("Авторизация")
        Form.resize(400, 310)
        Form.setStyleSheet("QWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.loginInput = QtWidgets.QLineEdit(Form)
        self.loginInput.setGeometry(QtCore.QRect(20, 70, 360, 21))
        self.loginInput.setStyleSheet("")
        self.loginInput.setInputMask("")
        self.loginInput.setObjectName("loginInput")
        self.loginLabel = QtWidgets.QLabel(Form)
        self.loginLabel.setGeometry(QtCore.QRect(20, 40, 360, 20))
        self.loginLabel.setStyleSheet("#loginLabel{\n"
"    font-family: \"Basier circle\",-apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\";\n"
"    font-size: 1.1rem;\n"
"    font-weight: 600;\n"
"    line-height: 1;\n"
"}")
        self.loginLabel.setObjectName("loginLabel")
        self.passwordLabel = QtWidgets.QLabel(Form)
        self.passwordLabel.setGeometry(QtCore.QRect(20, 110, 360, 20))
        self.passwordLabel.setStyleSheet("#passwordLabel{\n"
"    font-family: \"Basier circle\",-apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\";\n"
"    font-size: 1.1rem;\n"
"    font-weight: 600;\n"
"    line-height: 1;\n"
"}")
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordInput = QtWidgets.QLineEdit(Form)
        self.passwordInput.setGeometry(QtCore.QRect(20, 140, 360, 21))
        self.passwordInput.setInputMask("")
        self.passwordInput.setObjectName("passwordInput")
        self.loginButton = QtWidgets.QPushButton(Form)
        self.loginButton.setGeometry(QtCore.QRect(20, 200, 361, 31))
        self.loginButton.setStyleSheet("#loginButton{\n"
"  background-color: #fff;\n"
"   border: 1px solid #222222;\n"
"  border-radius: 8px;\n"
"  box-sizing: border-box;\n"
"  color: #0d172a;\n"
"  cursor: pointer;\n"
"  font-family: \"Basier circle\",-apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\";\n"
"  font-size: 1.1rem;\n"
"  font-weight: 600;\n"
"  line-height: 1;\n"
"  padding: 1rem 1.6rem;\n"
"  text-align: center;\n"
"  text-decoration: none #0d172a solid;\n"
"  text-decoration-thickness: auto;\n"
"  transition: all .1s cubic-bezier(.4, 0, .2, 1);\n"
"  box-shadow: 0px 1px 2px rgba(166, 175, 195, 0.25);\n"
"}\n"
"\n"
"#loginButton:hover {\n"
"  background-color: #1e293b;\n"
"  color: #fff;\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.signUpButton = QtWidgets.QPushButton(Form)
        self.signUpButton.setGeometry(QtCore.QRect(20, 240, 361, 31))
        self.signUpButton.setStyleSheet("#signUpButton{\n"
"  background-color: #FFFFFF;\n"
"  border: 1px solid #222222;\n"
"  border-radius: 8px;\n"
"  color: #222222;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: \"Basier circle\",-apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\";\n"
"  font-size: 1.1rem;\n"
"  font-weight: 600;\n"
"  line-height: 1;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 0px 23px;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  touch-action: manipulation;\n"
"  transition: box-shadow .2s,-ms-transform .1s,-webkit-transform .1s,transform .1s;\n"
"}\n"
"\n"
"#signUpButton:focus-visible {\n"
"  box-shadow: #222222 0 0 0 2px, rgba(255, 255, 255, 0.8) 0 0 0 4px;\n"
"  transition: box-shadow .2s;\n"
"}\n"
"\n"
"#signUpButton:active {\n"
"  background-color: #F7F7F7;\n"
"  border-color: #000000;\n"
"  transform: scale(.96);\n"
"}\n"
"\n"
"#signUpButton:disabled {\n"
"  border-color: #DDDDDD;\n"
"  color: #DDDDDD;\n"
"  cursor: not-allowed;\n"
"  opacity: 1;\n"
"}")
        self.signUpButton.setObjectName("signUpButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Вход"))
        self.loginLabel.setText(_translate("Form", "Введите логин:"))
        self.passwordLabel.setText(_translate("Form", "Введите пароль:"))
        self.loginButton.setText(_translate("Form", "Войти"))
        self.signUpButton.setText(_translate("Form", "Зарегистрироваться"))
