# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\design\signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignUp(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 421)
        Form.setStyleSheet("QWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.loginInput = QtWidgets.QLineEdit(Form)
        self.loginInput.setGeometry(QtCore.QRect(20, 90, 360, 21))
        self.loginInput.setStyleSheet("")
        self.loginInput.setInputMask("")
        self.loginInput.setObjectName("loginInput")
        self.loginLabel = QtWidgets.QLabel(Form)
        self.loginLabel.setGeometry(QtCore.QRect(20, 60, 360, 20))
        self.loginLabel.setStyleSheet("#loginLabel{\n"
"    font-family: \"Basier circle\",-apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\";\n"
"    font-size: 1.1rem;\n"
"    font-weight: 600;\n"
"    line-height: 1;\n"
"}")
        self.loginLabel.setObjectName("loginLabel")
        self.passwordLabel = QtWidgets.QLabel(Form)
        self.passwordLabel.setGeometry(QtCore.QRect(20, 200, 360, 20))
        self.passwordLabel.setStyleSheet("#passwordLabel{\n"
"    font-family: \"Basier circle\",-apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\";\n"
"    font-size: 1.1rem;\n"
"    font-weight: 600;\n"
"    line-height: 1;\n"
"}")
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordInput = QtWidgets.QLineEdit(Form)
        self.passwordInput.setGeometry(QtCore.QRect(20, 230, 360, 21))
        self.passwordInput.setInputMask("")
        self.passwordInput.setObjectName("passwordInput")
        self.signUpButton = QtWidgets.QPushButton(Form)
        self.signUpButton.setGeometry(QtCore.QRect(20, 350, 361, 31))
        self.signUpButton.setStyleSheet("#signUpButton{\n"
"  background-color: #FFFFFF;\n"
"  border: 1px solid #222222;\n"
"  border-radius: 8px;\n"
"  color: #222222;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: \"Basier circle\",-apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\";\n"
"  font-size: 1.1rem;\n"
"  font-weight: 600;\n"
"  line-height: 1;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 0px 23px;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  touch-action: manipulation;\n"
"  transition: box-shadow .2s,-ms-transform .1s,-webkit-transform .1s,transform .1s;\n"
"}\n"
"\n"
"#signUpButton:focus-visible {\n"
"  box-shadow: #222222 0 0 0 2px, rgba(255, 255, 255, 0.8) 0 0 0 4px;\n"
"  transition: box-shadow .2s;\n"
"}\n"
"\n"
"#signUpButton:active {\n"
"  background-color: #F7F7F7;\n"
"  border-color: #000000;\n"
"  transform: scale(.96);\n"
"}\n"
"\n"
"#signUpButton:disabled {\n"
"  border-color: #DDDDDD;\n"
"  color: #DDDDDD;\n"
"  cursor: not-allowed;\n"
"  opacity: 1;\n"
"}")
        self.signUpButton.setObjectName("signUpButton")
        self.repeatPasswordLabel = QtWidgets.QLabel(Form)
        self.repeatPasswordLabel.setGeometry(QtCore.QRect(20, 260, 360, 20))
        self.repeatPasswordLabel.setStyleSheet("#repeatPasswordLabel{\n"
"    font-family: \"Basier circle\",-apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\";\n"
"    font-size: 1.1rem;\n"
"    font-weight: 600;\n"
"    line-height: 1;\n"
"}")
        self.repeatPasswordLabel.setObjectName("repeatPasswordLabel")
        self.repeatPasswordInput = QtWidgets.QLineEdit(Form)
        self.repeatPasswordInput.setGeometry(QtCore.QRect(20, 290, 360, 21))
        self.repeatPasswordInput.setInputMask("")
        self.repeatPasswordInput.setObjectName("repeatPasswordInput")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(20, 180, 361, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.usernameLabel = QtWidgets.QLabel(Form)
        self.usernameLabel.setGeometry(QtCore.QRect(20, 120, 360, 20))
        self.usernameLabel.setStyleSheet("#usernameLabel{\n"
"    font-family: \"Basier circle\",-apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\";\n"
"    font-size: 1.1rem;\n"
"    font-weight: 600;\n"
"    line-height: 1;\n"
"}")
        self.usernameLabel.setObjectName("usernameLabel")
        self.usernameInput = QtWidgets.QLineEdit(Form)
        self.usernameInput.setGeometry(QtCore.QRect(20, 150, 360, 21))
        self.usernameInput.setStyleSheet("")
        self.usernameInput.setInputMask("")
        self.usernameInput.setText("")
        self.usernameInput.setObjectName("usernameInput")
        self.title = QtWidgets.QLabel(Form)
        self.title.setEnabled(True)
        self.title.setGeometry(QtCore.QRect(160, 20, 91, 20))
        self.title.setStyleSheet("#title{\n"
"    font-family: \"Basier circle\",-apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\";\n"
"    font-size: 2rem;\n"
"    font-weight: 600;\n"
"    line-height: 1;\n"
"}")
        self.title.setObjectName("title")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Регистрация"))
        self.loginLabel.setText(_translate("Form", "Введите логин:"))
        self.passwordLabel.setText(_translate("Form", "Введите пароль:"))
        self.signUpButton.setText(_translate("Form", "Зарегистрироваться"))
        self.repeatPasswordLabel.setText(_translate("Form", "Повторите пароль:"))
        self.usernameLabel.setText(_translate("Form", "Введите имя пользователя:"))
        self.title.setText(_translate("Form", "РЕГИСТРАЦИЯ"))
